### ISSUE TITLE
Is really x86 emulator? Great job

### ISSUE THREAD

**Issue by mediaexplorer74** [NiwakaDev/X86_EMULATOR_2#2]
Hi! Great work/job. Your C++ solution is impressive :)
Is X86_EMULATOR_2 more newest version of X86_EMULATOR?

**Comment by NiwakaDev** [comment]
Thank you for your message . 
Is X86_EMULATOR_2 more newest version of X86_EMULATOR?
->Yes .

**Comment by mediaexplorer74** [comment]
> Thank you for your message . Is X86_EMULATOR_2 more newest version of X86_EMULATOR? ->Yes .

Cool!
Thank you very much for some important references/articles (in English) and for Readme.md maintanence :)

**Comment by NiwakaDev** [comment]
I have written an README.md in English .(Sorry for my poor English) If you have any questions, feel free to contact me .
